name: coast_audio_miniaudio
description: An extension package for coast_audio using miniaudio.
version: 0.0.2
repository: https://github.com/SKKbySSK/coast_audio/tree/main/packages/coast_audio_miniaudio

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  ffi: ^2.1.0
  coast_audio: ^0.0.3

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.1.1
  test: ^1.24.8

ffigen:
  name: 'MaBridge'
  output: 'lib/generated/ma_bridge_bindings.dart'
  headers:
    entry-points:
      - 'mabridge/src/**.h'
